### ISSUE TITLE
Consider swaping to ES6

### ISSUE THREAD

**Issue by rymatech** [fac-17/IJKL-week2-project#23]
ES6 is very common and does not take too long to learn. Perhaps try converting your functions to ES6 

Function demonstration() {
}

const demonstration = () => {
}

Function anotherOne(a) {
}

const anotherOne = a => {
}

function anotherAnotherOne(a, b) {
}

const anotherAnotherOne = (a, b) => {
}

**Comment by rooberrydev** [comment]
good call ryan!
we were working on a skeleton codebase which had the function declarations pre-written for us.
Just had to fill in the logic inside. so converting the declarations to es6 syntax never crossed our minds oops.
